"""Download the site's typefaces so no third party is contacted on page load.

Google Fonts is convenient, but it means Google receives every visitor's IP
address on every page. Browsers stopped sharing font caches between sites years
ago, so hosting the files ourselves costs nothing in speed and removes a third
party from the privacy notice entirely.

Only what the site actually uses is downloaded:
  - the latin subset only, because no character on the site needs latin-ext
  - Inter at 400, 600 and 700, and Marcellus at 400

Re-run this if the typefaces or weights change, or if content ever needs
accented characters (macrons in transliteration, say) - then add "latin-ext"
to SUBSETS.

    python scripts/fetch_fonts.py
"""

import os
import re
import sys
import urllib.request

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Marcellus&family=Inter:wght@400;600;700&display=swap")
SUBSETS = ("latin",)
FONT_DIR = "assets/fonts"
OUT_CSS = "css/fonts.css"

# Google serves woff2 only to browsers that advertise support.
UA = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"}


def get(url, headers=None):
    return urllib.request.urlopen(
        urllib.request.Request(url, headers=headers or {}), timeout=30).read()


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = get(CSS_URL, UA).decode("utf-8")

    blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
    wanted = [(sub, b) for sub, b in blocks if sub in SUBSETS]
    if not wanted:
        print("no matching font faces returned - has the Google Fonts API changed?", file=sys.stderr)
        return 1

    lines = [
        "/* Typefaces served from this site, not from Google.",
        "   Generated by scripts/fetch_fonts.py - edit that, not this file. */",
        "",
    ]
    total = 0
    for subset, block in wanted:
        family = re.search(r"font-family: '([^']+)'", block).group(1)
        weight = re.search(r"font-weight: (\d+)", block).group(1)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block).group(1)

        filename = f"{family.lower().replace(' ', '-')}-{weight}.woff2"
        path = os.path.join(FONT_DIR, filename)
        open(path, "wb").write(get(url, UA))
        total += os.path.getsize(path)

        # font-display: swap keeps text visible while the file loads.
        lines.append(block.replace(url, f"../{FONT_DIR}/{filename}"))
        lines.append("")
        print(f"  {family} {weight} ({subset}) -> {filename}  {os.path.getsize(path) // 1024}KB")

    open(OUT_CSS, "w", encoding="utf-8").write("\n".join(lines))
    print(f"wrote {OUT_CSS} and {len(wanted)} font file(s), {total // 1024}KB total")
    return 0


if __name__ == "__main__":
    sys.exit(main())
